config/routes.rb
Animurecs::Application.routes.draw do
  resources :show_aliases

  resources :list_entries

  resources :lists

  resources :sessions, :only => [:new, :create, :destroy]
  resources :tagtypes
  resources :tags do
	  get :autocomplete_tag_name, :on => :collection
  end
  resources :shows do 
    member do
      get :taggings, :taggeds
    end
  end
  resources :taggings, :users, :comments, :showvotes

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/connect', :to => 'pages#connect'
  match '/discover', :to => 'shows#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/comments/new/:show_id',	:to => 'comments#new'
  match '/taggings/new/:show_id',	:to => 'taggings#new'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :list_entries
  # attr_accessible :title, :body
  validates :user_id, :presence => true

  def list_entries=(hash)
    hash.each do |sequence,list_entry|
      unless list_entry.nil? || list_entry.empty?
        new_entry = ListEntry.find_or_initialize_by_list_id_and_show_id(list_entry[:list_id], list_entry[:show_id])
        if can? :update, new_entry
          new_entry = list_entry
          new_entry.save!
        end
      end
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  load_and_authorize_resource
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    if params[:user_id].nil?
      @list = List.find(params[:id])
    else
      @list = User.find(params[:user_id]).lists.first
    end

    respond_to do |format|
      format.js
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<% if current_user?(@list.user) %>
<div class='row-fluid'>
  <div class='span7' id='list-entry-form'></div>
</div>
<div class='row-fluid'>
  <div class='span12' id='list-add-entry-button'>
    <%= link_to raw("<i class='icon-plus-sign'></i>Add a new entry"), new_list_entry_path(:format => :js, :list_id => @list.id), :remote=>true %>
  </div>
</div>
<% end %>
<table id='user_list' class='table table-striped table-bordered'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Score</th>
    <th>Comment</th>
  </tr>
  </thead>
  <tbody>
  <% @list.list_entries.each do |list_entry| %>
    <tr>
      <td><%= link_to list_entry.show.name, list_entry.show %></td>
      <td></td>
      <td><%= list_entry.score %></td>
      <td><%= list_entry.comment %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.user_id %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Score</th>
      <th>Comment</th>
    </tr>
  </thead>
  <tbody>
    <% @list.list_entries.each do |list_entry| %>
    <tr>
      <td><%= link_to list_entry.show.name, list_entry.show %></td>
      <td></td>
      <td><%= list_entry.score %></td>
      <td><%= list_entry.comment %></td>
    </tr>
    <% end %>
  </tbody>
</table>