config/routes.rb
Animurecs::Application.routes.draw do
  resources :show_aliases

  resources :list_entries

  resources :lists

  resources :sessions, :only => [:new, :create, :destroy]
  resources :tagtypes
  resources :tags do
	  get :autocomplete_tag_name, :on => :collection
  end
  resources :shows do 
    member do
      get :taggings, :taggeds
    end
  end
  resources :taggings, :users, :comments, :showvotes

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/connect', :to => 'pages#connect'
  match '/discover', :to => 'shows#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/comments/new/:show_id',	:to => 'comments#new'
  match '/taggings/new/:show_id',	:to => 'taggings#new'

end

app/controllers/show_aliases_controller.rb
class ShowAliasesController < ApplicationController
  load_and_authorize_resource
  # GET /show_aliases
  # GET /show_aliases.json
  def index
    @show_aliases = ShowAlias.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @show_aliases }
    end
  end

  # GET /show_aliases/1
  # GET /show_aliases/1.json
  def show
    @show_alias = ShowAlias.find(params[:id])
    respond_to do |format|
      format.html { redirect_to @show_alias.show }
      format.json { render json: @show_alias }
    end
  end

  # GET /show_aliases/new
  # GET /show_aliases/new.json
  def new
    @show_alias = ShowAlias.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show_alias }
    end
  end

  # GET /show_aliases/1/edit
  def edit
    @show_alias = ShowAlias.find(params[:id])
  end

  # POST /show_aliases
  # POST /show_aliases.json
  def create
    @show_alias = ShowAlias.new(params[:show_alias])

    respond_to do |format|
      if @show_alias.save
        format.html { redirect_to @show_alias, notice: 'Show alias was successfully created.' }
        format.json { render json: @show_alias, status: :created, location: @show_alias }
      else
        format.html { render action: "new" }
        format.json { render json: @show_alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /show_aliases/1
  # PUT /show_aliases/1.json
  def update
    @show_alias = ShowAlias.find(params[:id])

    respond_to do |format|
      if @show_alias.update_attributes(params[:show_alias])
        format.html { redirect_to @show_alias, notice: 'Show alias was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show_alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /show_aliases/1
  # DELETE /show_aliases/1.json
  def destroy
    @show_alias = ShowAlias.find(params[:id])
    @show_alias.destroy

    respond_to do |format|
      format.html { redirect_to show_aliases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/show_aliases_helper.rb
module ShowAliasesHelper
end

app/views/show_aliases/_form.html.erb
<%= form_for(@show_alias) do |f| %>
  <% if @show_alias.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show_alias.errors.count, "error") %> prohibited this show_alias from being saved:</h2>

      <ul>
      <% @show_alias.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :show %><br />
    <%= f.text_field :show %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/show_aliases/edit.html.erb
<h1>Editing show_alias</h1>

<%= render 'form' %>

<%= link_to 'Show', @show_alias %> |
<%= link_to 'Back', show_aliases_path %>

app/views/show_aliases/index.html.erb
<h1>Listing show_aliases</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Show</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @show_aliases.each do |show_alias| %>
  <tr>
    <td><%= show_alias.name %></td>
    <td><%= show_alias.show %></td>
    <td><%= link_to 'Show', show_alias %></td>
    <td><%= link_to 'Edit', edit_show_alias_path(show_alias) %></td>
    <td><%= link_to 'Destroy', show_alias, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Show alias', new_show_alias_path %>

app/views/show_aliases/new.html.erb
<h1>New show_alias</h1>

<%= render 'form' %>

<%= link_to 'Back', show_aliases_path %>

app/views/show_aliases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @show_alias.name %>
</p>

<p>
  <b>Show:</b>
  <%= @show_alias.show %>
</p>


<%= link_to 'Edit', edit_show_alias_path(@show_alias) %> |
<%= link_to 'Back', show_aliases_path %>