config/routes.rb
Animurecs::Application.routes.draw do
  resources :show_aliases

  resources :list_entries

  resources :lists

  resources :sessions, :only => [:new, :create, :destroy]
  resources :tagtypes
  resources :tags do
	  get :autocomplete_tag_name, :on => :collection
  end
  resources :shows do 
    member do
      get :taggings, :taggeds
    end
  end
  resources :taggings, :users, :comments, :showvotes

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/connect', :to => 'pages#connect'
  match '/discover', :to => 'shows#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/comments/new/:show_id',	:to => 'comments#new'
  match '/taggings/new/:show_id',	:to => 'taggings#new'

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	attr_accessor :tagtext
	belongs_to	:tag
	
	validates :show_id,	:presence => true,
						:numericality => true

	validates :tag_id,	:presence => true,
						:numericality => true

end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  load_and_authorize_resource
  # Displays list of taggings.
  # Can be accessed by GETting /taggings or  /taggings.xml
  def index
    @taggings = Tagging.all
	@title = "Taggings"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @taggings }
    end
  end

  # Displays a tagging's information.
  # Can be accessed by GETting /taggings/1 or  /taggings/1.xml
  def show
    @tagging = Tagging.find(params[:id])
	@tag = Tag.find(@tagging.tag_id)
	@show = Show.find(@tagging.show_id)
	@title = "Tagging " + @tag.name + "-" + @show.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tagging }
    end
  end

  # Displays the form to add a new tagging.
  # Can be accessed by GETting /taggings/new or  /taggings/new.xml
  def new
    @tagging = Tagging.new
	@title = "New tagging"
	
	unless params[:show_id].nil?
		@show = Show.find(params[:show_id])
		@tagging.show_id = @show.id
	else
		@show = Show.first
	end
	@tagging.tagtext = ""

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tagging }
    end
  end

  # Displays the form to edit a tagging's information.
  # Can be accessed by GETting /taggings/edit/1
  def edit
    @tagging = Tagging.find(params[:id])
	@tag = Tag.find(@tagging.tag_id)
	@show = Show.find(@tagging.show_id)
	@title = "Editing " + @tag.name + "-" + @show.name
  end

  # Creates a tagging.
  # Can be accessed by POSTing to /taggings or  /taggings.xml
  def create
	# process the tag to see if we have a text tagtype in there.
	if params[:tagging][:tagtext].include? ":"
		# lop off the first bit as the tag type and the second bit as the actual tag name.
		tagarray = params[:tagging][:tagtext].split(":")
		if Tagtype.find_by_name(tagarray[0])
			tagtype_id = Tagtype.find_by_name(tagarray[0]).id
			tagtext = tagarray.last(tagarray.length-1).join(":")
		else
			tagtype_id = Tagtype.find_by_name("general")
			tagtext = tagarray.last(tagarray.length).join(":")
		end
	else
		tagtype_id = Tagtype.find_by_name("general").id
		tagtext = params[:tagging][:tagtext]
	end
	# replace whitespace with an underscore.
	tagtext.gsub!(/\s+/, '_')
	# save this tag into the db, if it doesn't already exist.
	oldtag = Tag.find_by_name(tagtext)
	if oldtag.nil? 
		newtag = Tag.new(:name => tagtext, :description => "", :tagtype_id => tagtype_id)
		newtag.save
	else
		newtag = oldtag
	end
	# now set the tag id in params and save this as a new tag.
	params[:tagging][:tag_id] = newtag.id
	@tagging = Tagging.new(params[:tagging])
	@show = Show.find(@tagging.show_id)
	
    respond_to do |format|
      if @tagging.save
        format.html { redirect_to(@tagging, :notice => 'Tagging was successfully created.') }
        format.xml  { render :xml => @tagging, :status => :created, :location => @tagging }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tagging.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Updates a tagging with new information.
  # Can be accessed by PUTting /taggings/1 or  /taggings/1.xml
  def update
    @tagging = Tagging.find(params[:id])

    respond_to do |format|
      if @tagging.update_attributes(params[:tagging])
        format.html { redirect_to(@tagging, :notice => 'Tagging was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tagging.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Deletes a tagging.
  # Can be accessed by DELETEing /taggings/1 or  /taggings/1.xml
  def destroy
    @tagging = Tagging.find(params[:id])
    @tagging.destroy

    respond_to do |format|
      format.html { redirect_to(taggings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/taggings/_form.html.erb
<%= form_for(@tagging) do |f| %>
  <% if @tagging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tagging.errors.count, "error") %> prohibited this tagging from being saved:</h2>

      <ul>
      <% @tagging.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">  
	<% if @show.nil? %>
    <%= f.hidden_field :show_id, :value => Show.first.id %>
	<% else %>
    <%= f.hidden_field :show_id, :value => @show.id %>
	<% end %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br />
    <%= f.text_field :tagtext, :autocomplete => autocomplete_tag_name_tags_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taggings/edit.html.erb
<h1>Editing tagging</h1>

<%= render 'form' %>

<%= link_to 'Show', @tagging %> |
<%= link_to 'Back', taggings_path %>

app/views/taggings/index.html.erb
<h1>Listing taggings</h1>

<table>
  <tr>
    <th>Show</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taggings.each do |tagging| %>
  <tr>
    <td><%= Show.find(tagging.show_id).name %></td>
    <td><%= Tag.find(tagging.tag_id).name %></td>
    <td><%= link_to 'Show', tagging %></td>
    <td><%= link_to 'Edit', edit_tagging_path(tagging) %></td>
    <td><%= link_to 'Destroy', tagging, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tagging', new_tagging_path %>

app/views/taggings/new.html.erb
<h1>New tagging<% unless @show.nil? %> for <%= @show.name %><% end %></h1>

<%= render 'form' %>

<%= link_to 'Back', taggings_path %>

app/views/taggings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Show:</b>
  <%= Show.find(@tagging.show_id).name %>
</p>

<p>
  <b>Tag:</b>
  <%= Tag.find(@tagging.tag_id).name %>
</p>


<%= link_to 'Edit', edit_tagging_path(@tagging) %> |
<%= link_to 'Back', taggings_path %>