config/routes.rb
Animurecs::Application.routes.draw do
  resources :show_aliases

  resources :list_entries

  resources :lists

  resources :sessions, :only => [:new, :create, :destroy]
  resources :tagtypes
  resources :tags do
	  get :autocomplete_tag_name, :on => :collection
  end
  resources :shows do 
    member do
      get :taggings, :taggeds
    end
  end
  resources :taggings, :users, :comments, :showvotes

  root :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/connect', :to => 'pages#connect'
  match '/discover', :to => 'shows#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/comments/new/:show_id',	:to => 'comments#new'
  match '/taggings/new/:show_id',	:to => 'taggings#new'

end

app/views/layouts/_footer.html.erb
				<footer>
				  <nav class="round">
					<ul>
					  <li><%= link_to "About", about_path %></li>
					  <li><%= link_to "Contact", contact_path %></li>
					</ul>
				  </nav>
					<script type="text/javascript">

					  var _gaq = _gaq || [];
					  _gaq.push(['_setAccount', 'UA-23155718-1']);
					  _gaq.push(['_trackPageview']);

					  (function() {
						var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
						ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
						var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
					  })();

					</script>
				</footer>

app/views/layouts/_header.html.erb
		<header>
		  <div id = "header_inner">
			  <nav class="round signin">
				<ul>
				  <% if signed_in? %>
				  <li><%= link_to "Profile", @current_user %></li>
				  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
				  <% else %>
				  <li><%= link_to "Sign in", signin_path %></li>
				  <% end %>
				</ul>
			  </nav>
			  <div id = "logo_search">
				  <%= link_to logo, root_path %>
				  <%= render 'layouts/search' %>
			  </div>
		  </div>
		</header>
		<div id = "mainmenu">
<%= render 'layouts/mainmenu' %>
		</div><br /><br />
		<div id="content">
<% if @popularTags %>
			<div id="sidebar">  
				<div style="margin-bottom: 1em;">
					<h5>Tags</h5>
					<div id="sidebar-tags">
						<%= show_tag_sidebar(@popularTags) %>
					</div>      
				</div>
			</div>
<% end %>
			<div id="ads">
			</div>

app/views/layouts/_mainmenu.html.erb
			<div id = 'mainmenu_inner'>
				<nav>
					<ul>
						<li><%= link_to "Shows", shows_path %></li>
						<li><%= link_to "Tags", tags_path %></li>
						<li><%= link_to "Comments", comments_path %></li>
						<li><%= link_to "Users", users_path %></li>
					</ul>
				</nav>
			</div>

app/views/layouts/_search.html.erb
                  <%= form_tag '/shows', :id => "home_search", :class=> 'form-search', :method => 'get' do %>
          <div class='input-append'>
            <%= text_field_tag :tags, params[:tags], :size => 8, :class => 'input-medium search-query', :id => 'searchform_q', :autocomplete => autocomplete_tag_name_tags_path, :"data-delimiter" => ' ' %>
            <%= button_tag "Search", :class => 'btn', :type => 'button', :id => 'searchform_submit' %>
          </div>
		  <% end %>

app/views/layouts/_sidebar.html.erb
      <div id="sidebar">
        <% if @user %>
          <div id = 'userprofile' class="sidebar">
            <%= avatar_image %>
            <% if can? :edit, @user %><br />
            <%= link_to 'Edit', edit_user_path(@user) %> |
            <% end %>
          </div>
        <% elsif @show %>
        <div id="showprofile" class="sidebar">
          <%= show_image %>
          <% if can? :edit, @show %><br />
          <%= link_to 'Edit Anime Information', edit_show_path(@show) %><br />
          <% end
          if can? :destroy, @show %>
          <%= link_to 'Delete Anime', @show, :confirm => 'Are you sure you want to delete show: ' + @show.name + '?', :method => :delete %>
          <% end %><br />
        <% end %>
        <% if @popularTags %>
          <h5>Tags</h5>
          <%= render 'layouts/search' %>
          <div id="sidebar-tags">
            <%= show_tag_sidebar(@popularTags) %>
          </div>
        <% end %>
        <% if @show %>
        </div>
        <% end %>
      </div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'jquery-ui-1.8.16.custom.css'%>

app/views/layouts/_topbar.html.erb
                  <div class="navbar navbar-fixed-top">
                    <div class='navbar-inner'>
                      <div class='container-fluid'>
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>
                        <% if signed_in? %>
                          <%= link_to "Animurecs", user_path(current_user), :class => "brand" %>
                          <div class="nav-collapse">
                            <ul class="nav">
                              <li><%= link_to "Home", user_path(current_user), :class=>"home" %></li>
                      <% else %>
                          <%= link_to "Animurecs", root_path, :class => "brand" %>
                          <div class="nav-collapse">
                            <ul class="nav">
                              <li><%= link_to "Home", home_path, :class=>"home" %></li>
                      <% end %>
                            <li><%= link_to "Connect", users_path, :class=>"connect" %></li>
                            <li><%= link_to "Discover", discover_path, :class=>"discover" %></li>
                          </ul>
                          <ul class="nav pull-right">
                            <li class="dropdown">
                            <% if signed_in? %>
                              <%= render :partial => 'users/notification_bubble', :locals => {:user => current_user} %>
                              <div id="global_notifications" class="dropdown-menu">
                                peekaboo :3
                              </div>
                              <script type="text/javascript">$('#global_notification_bubble').click(function(){$('#global_notifications').toggle();});</script>
                            </li>
                            <li class="dropdown">
                              <%= link_to user_header_profile_pic, '#', :id=>"header_profile_pic" %>
                              <div id="mini-profile" class="dropdown-menu">
                                <h2><%= @current_user.username %></h2>
                                <ul>
                                  <li><%= link_to "Profile", user_path(@current_user) %></li>
                                  <li><%= link_to "Sign out", signout_path, :class=>"signout_link" %></li>
                                </ul>
                              </div>
                              <script type="text/javascript">$('#header_profile_pic').click(function(){$('#mini-profile').toggle();});</script>
                            <% else %>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                  <%= render :partial => 'sessions/form' %>
                                </ul>
                              <% end %>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class='container-fluid'>
      <%= render 'layouts/topbar' %>
      <div class='row-fluid'>
        <% if @show or @popularTags or @user %>
        <div class='span3'>
          <%= render 'layouts/sidebar' %>
        </div>
        <div class='span8'>
        <% else %>
        <div class='span11'>
        <% end %>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <button class="close" data-dismiss="alert">×</button>
            <%= value %>
          </div>
        <% end %>
          <%= yield %>
        </div>
        <div class='span1' id="ads">
          Nothing to see here.
        </div>
      </div>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>